openapi: 3.0.0
info:
  version: 1.0.0
  title: Project Milestone 2
  description: Task manager webs app with RESTful API
servers:
  - url: https://week11-rpb.up.railway.app
    description: 'production server'
  - url: http://localhost:4000
    description: 'Development server'
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Bearer with JWT Token'
  schemas:
    RegisterUser:
      type: object
      properties:
        username:
          type: string
          default: jawir
        password:
          type: string
          minLength: 8
          default: alphanumeric1
        role:
          description: Possible values for roles are manager and employee.
          type: string 
          enum:
            - manager
            - employee
          default: employee
      required:
        - username
        - password
        - role
    LoginUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    CreateTask:
      type: object
      properties:
        task:
          type: string 
      required:
        - task     
    BadRequest:
      type: object
      properties:
        success:
          type: boolean
          default: false
        error:
          type: string
    InternalServerError:
      type: object
      properties:
        error:
          type: string
    Unauthorized:
      type: object
      properties:
        error:
          type: string
    NotFound:
      type: object
      properties:
        success:
          type: boolean 
          default: false 
        message:
          type: string
paths:
  /v1/auth/login:
    post:
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            example:
              username: rpb
              password: manager123
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
  /v1/auth/register:
    post:
      summary: Register user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
            example:
              username: aaaaa
              password: aaaa1111
              role: employee
      responses:
        '200':
          description: Successful response
        '400':
          description: Wrong input requirement
  /v1/users:
    get:
      summary: Get all user
      parameters: []
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal Server Error
  /v1/users/{userId}:
    get:
      summary: Get one user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '400':
          description: Wrong input format of UserId
        '404':
          description: User not found
        '500':
          description: Internal Server Error
    delete:
      summary: Delete one user
      security:
        - bearer_auth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: User not found
        '500':
          description: Internal Server Error
    patch:
      summary: Update user
      security:
        - bearer_auth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
            example:
              username: notnull
              password: alphaNumeric1
              role: employee
      responses:
        '200':
          description: Successful response
        '404':
          description: User not found
        '500':
          description: Internal Server Error
  /v1/tasks:
    post:
      summary: Create new task
      security:
        - bearer_auth: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
            example:
              task: make weekly report
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    get:
      summary: Get all tasks
      security:
        - bearer_auth: []
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal Server Error
  /v1/tasks/{taskId}:
    get:
      summary: Get one task
      security:
        - bearer_auth: []
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Task not found
        '500':
          description: Internal Server Error
    patch:
      summary: Update task status
      security:
        - bearer_auth: []      
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
            example:
              status: In progress
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad Request
        '404':
          description: Task not found
        '500':
          description: Internal Server Error
    delete:
      summary: Soft delete task
      security:
        - bearer_auth: []
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Task not found
        '500':
          description: Internal Server Error
  /:
    get:
      summary: Rest API home
      responses:
        '200':
          description: Successful response
